#!/usr/bin/env python3
"""
Quick test to generate one article and verify the system works
"""
import os
import sys
from pathlib import Path

# Set environment variables
os.environ['NEWSAPI_KEY'] = 'b86bc01720554a51a966fc3c72af5dda'
os.environ['GNEWS_API_KEY'] = 'd41d8a047305a163373d164e3bb43cbe'

# Add src to path
sys.path.insert(0, str(Path(__file__).parent))

def quick_test():
    """Quick test to generate one article"""
    print("🧪 Quick Article Generation Test")
    print("=" * 50)
    
    # Create directories
    Path("generated_articles").mkdir(exist_ok=True)
    Path("memory_store").mkdir(exist_ok=True)
    
    # Test 1: Check imports
    print("\n1️⃣ Testing imports...")
    try:
        from src.agents.collector import CollectorAgent
        print("   ✅ CollectorAgent imported")
    except Exception as e:
        print(f"   ❌ Failed: {e}")
        return False
    
    # Test 2: Collect one article
    print("\n2️⃣ Collecting one article...")
    try:
        collector = CollectorAgent()
        articles = collector.collect_news(
            categories=["technology"],
            page_size=5,
            pages=1
        )
        
        if articles and len(articles) > 0:
            print(f"   ✅ Collected {len(articles)} articles")
            print(f"   Sample: {articles[0].get('title', 'N/A')[:50]}...")
            
            # Save as simple markdown
            article = articles[0]
            filename = f"generated_articles/test_article_{article.get('title', 'untitled')[:30].replace(' ', '_')}.md"
            
            content = f"""# {article.get('title', 'Untitled')}

**Source:** {article.get('source', {}).get('name', 'Unknown')}
**Published:** {article.get('publishedAt', 'Unknown')}
**URL:** {article.get('url', 'N/A')}

## Description

{article.get('description', 'No description available.')}

## Content

{article.get('content', 'No content available.')}

---
*Generated by AI Content Intelligence Platform*
"""
            
            Path(filename).write_text(content, encoding='utf-8')
            print(f"   ✅ Saved to: {filename}")
            return True
        else:
            print("   ⚠️  No articles collected (API limit or error)")
            return False
            
    except Exception as e:
        print(f"   ❌ Failed: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = quick_test()
    
    if success:
        print("\n" + "=" * 50)
        print("✅ SUCCESS! Article generated!")
        print("Check the 'generated_articles' folder")
    else:
        print("\n" + "=" * 50)
        print("⚠️  Test failed - check errors above")
